version: "3"
services:
  # PostgreSQL 数据库
  db:
    image: "postgres:13"
    container_name: tethys-db
    networks:
      - backend
    environment:
      POSTGRES_USER: "tethys"
      POSTGRES_PASSWORD: "123456"

  # 数据库 schema 更新
  db-migration:
    image: kevin70/tethys-db-migration
    container_name: tethys-db-migration
    networks:
      - backend
    environment:
      FLYWAY_URL: "jdbc:postgresql://db/tethys"
      FLYWAY_USER: "tethys"
      FLYWAY_PASSWORD: "123456"
    command: migrate
    depends_on:
      - db

  #  IM 推送服务
  im:
    image: kevin70/tethys-im
    container_name: tethys-im
    networks:
      - backend
    ports:
      - 11010:11010
    environment:
      TETHYS_MESSAGE_STORAGE_R2DBC_URL: "r2dbc:postgresql://tethys:123456@db/tethys"
    depends_on:
      - db-migration

  # IM REST 服务
  rest:
    image: kevin70/tethys-rest
    container_name: tethys-rest
    networks:
      - backend
    ports:
      - 11019:11019
    environment:
      TETHYS_MESSAGE_STORAGE_R2DBC_URL: "r2dbc:postgresql://tethys:123456@db/tethys"
    depends_on:
      - db-migration
networks:
  backend: