version: "3"
services:
  # PostgreSQL 数据库
  db:
    image: "postgres:13"
    container_name: tethys-db
    networks:
      - backend
    environment:
      POSTGRES_USER: "tethys"
      POSTGRES_PASSWORD: "123456"
  # 数据库 schema 更新
  db-migration:
    image: kevin70/tethys-db-migration
    container_name: tethys-db-migration
    networks:
      - backend
    environment:
      FLYWAY_URL: "jdbc:postgresql://db/tethys"
      FLYWAY_USER: "tethys"
      FLYWAY_PASSWORD: "123456"
    entrypoint: sh
    command: -c "wait-for db:5432 && flyway migrate"
    depends_on:
      - db
  # 逻辑服务
  logic:
    image: kevin70/tethys-server-logic
    container_name: tethys-server-logic
    networks:
      - backend
    ports:
      - 11010:11010
    environment:
      TETHYS_MESSAGE_STORAGE_R2DBC_URL: "r2dbc:postgresql://tethys:123456@db/tethys"
    depends_on:
      - db-migration
  # REST 服务
  rest:
    image: kevin70/tethys-server-rest
    container_name: tethys-server-rest
    networks:
      - backend
    ports:
      - 11019:11019
    environment:
      TETHYS_MESSAGE_STORAGE_R2DBC_URL: "r2dbc:postgresql://tethys:123456@db/tethys"
    depends_on:
      - db-migration
  # WebSocket 服务
  ws:
    image: kevin70/tethys-server-ws
    container_name: tethys-server-ws
    networks:
      - backend
    ports:
      - 11012:11012
networks:
  backend: