openapi: "3.0.3"
info:
  version: 1.0.0
  title: Tethys REST RESTful 接口
servers:
  - url: http://localhost:11019/
tags:
  - name: TEST
    description: 测试专用
  - name: MESSAGE
    description: IM 消息
  - name: PRIVATE-MESSAGE
    description: 私人消息
  - name: GROUP-MESSAGE
    description: 群组消息
paths:
  /token/{uid}:
    parameters:
      - name: uid
        in: path
        required: true
        description: 用户 ID
        schema:
          type: integer
          format: int64
    post:
      tags: [TEST]
      summary: 生成用户访问令牌
      description: |
        **测试专用** 快速通过用户 ID 生成访问令牌
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - access_token
                properties:
                  access_token:
                    type: string
                    description: 访问令牌
  /message-ids:
    get:
      parameters:
        - name: limit
          in: query
          description: 返回 ID 的最大数量
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
      tags: [MESSAGE]
      security: [AccessToken:[]]
      summary: 获取 IM 消息 ID
      description: |
        返回 IM 消息 ID 列表，该列表中的 ID 用于在后续聊天消息中使用，每个 ID 仅可使用一次。
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: IM 消息 ID
  /private-messages/recent:
    get:
      tags: [PRIVATE-MESSAGE]
      security: [AccessToken:[]]
      summary: 最近的私聊消息查询
      description: |
        如果返回的消息数组的长度小于 `limit` 请求查询参数值，则代表服务端没有更多的消息不需要继续查询，反之则
        代表服务端还有更多的消息，客户端需要继续调用些接口拉取私聊信息，直到消息数组的长度小于 `limit`。
      parameters:
        - name: create_time
          in: query
          description: |
            私聊消息最早的创建时间。

            创建时间仅支持`3天（72小时）`以内的消息查询，时间超出范围将默认当前时间之前的72小时为查询时间。
          schema:
            type: string
            format: date-time
        - name: offset
          in: query
          description: 查询偏移量
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: 返回最大的条数
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 500
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PrivateMessage"
  /private-messages/read-status/batch:
    put:
      tags: [PRIVATE-MESSAGE]
      security: [AccessToken:[]]
      summary: 批量更新消息已读状态
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - message_ids
              properties:
                message_ids:
                  type: array
                  description: 消息 ID 列表，同时最大支持 100 条消息的已读状态更新
                  maxItems: 100
                  items:
                    type: string
                    default: 7K3JDMVTALDF3U
      responses:
        "204":
          description: OK
  /group-messages/recent:
    get:
      tags: [GROUP-MESSAGE]
      security: [AccessToken:[]]
      summary: 最近的群组消息查询
      description: |
        如果返回的消息数组的长度小于 `limit` 请求查询参数值，则代表服务端没有更多的消息不需要继续查询，反之则
        代表服务端还有更多的消息，客户端需要继续调用些接口拉取私聊信息，直到消息数组的长度小于 `limit`。
      parameters:
        - name: group_id
          in: query
          description: 群组 ID
          schema:
            type: string
          required: true
        - name: create_time
          in: query
          description: |
            群组消息最早的创建时间。

            创建时间仅支持`3天（72小时）`以内的消息查询，时间超出范围将默认当前时间之前的72小时为查询时间。
          schema:
            type: string
            format: date-time
        - name: offset
          in: query
          description: 查询偏移量
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: 返回最大的条数
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 500
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GroupMessage"
components:
  securitySchemes:
    AccessToken:
      type: apiKey
      description: 访问令牌
      name: access_token
      in: query
  schemas:
    PrivateMessage:
      type: object
      required:
        - id
        - sender_id
        - receiver_id
        - content
        - create_time
      properties:
        id:
          type: string
          description: 消息 ID，全局唯一
          example: 7K3JDMVTALDF3U
        sender_id:
          type: string
          description: 消息发送者 ID
        receiver_id:
          type: string
          description: 消息接收者 ID
        kind:
          type: integer
          enum: [1, 2, 3, 4]
          default: 1
          description: |
            消息类型
            - `1` 普通文本消息
            - `2` 图片消息
            - `3` 音频消息
            - `4` 视频消息
        content:
          type: string
          description: 消息内容
        url:
          type: string
          description: 统一资源定位器（图片URL、视频URL）
        custom_args:
          type: string
          description: 自定义参数
        unread:
          type: integer
          default: 1
          description: |
            消息是否未读
            - `1` 未读
            - `0` 已读
        create_time:
          type: string
          format: date-time
          description: 消息创建时间
    GroupMessage:
      type: object
      required:
        - id
        - group_id
        - sender_id
        - content
        - create_time
      properties:
        id:
          type: string
          description: 消息 ID，全局唯一
          example: 7K3JDMVTALDF3U
        group_id:
          type: string
          description: 群组 ID
        sender_id:
          type: string
          description: 消息发送者 ID
        kind:
          type: integer
          enum: [1, 2, 3, 4]
          default: 1
          description: |
            消息类型
            - `1` 普通文本消息
            - `2` 图片消息
            - `3` 音频消息
            - `4` 视频消息
        content:
          type: string
          description: 消息内容
        url:
          type: string
          description: 统一资源定位器（图片URL、视频URL）
        custom_args:
          type: string
          description: 自定义参数
        create_time:
          type: string
          format: date-time
          description: 消息创建时间