openapi: "3.0.3"
info:
  version: 1.0.0
  title: Tethys IM RESTful 接口
servers:
  - url: http://localhost:11010/
tags:
  - name: test
    description: 测试专用
paths:
  /token/{uid}:
    parameters:
      - name: uid
        in: path
        required: true
        description: 用户 ID
        schema:
          type: integer
          format: int64
    post:
      tags: [test]
      summary: 生成用户访问令牌
      description: |
        **测试专用** 快速通过用户 ID 生成访问令牌
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - access_token
                properties:
                  access_token:
                    type: string
                    description: 访问令牌
