name: Tethys CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: 123456
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        ###------------ 安装 psql
      - run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
        ###------------ 创建数据库
      - run: |
          psql -h localhost -U postgres -c 'create database tethys;'
        env:
          PGPASSWORD: 123456
        ###------------ FlywayDB 配置文件
      - run: mv flyway.conf.template flyway.conf
      - run: ./gradlew :flywayMigrate
        ###------------ 项目构建
      - run: ./gradlew build
      - run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v1
        with:
          files: |
            tethys-api/build/reports/jacoco/test/jacocoTestReport.xml,
            tethys-core/build/reports/jacoco/test/jacocoTestReport.xml,
            tethys-im-server/build/reports/jacoco/test/jacocoTestReport.xml,
            tethys-rest-server/build/reports/jacoco/test/jacocoTestReport.xml,
            tethys-repository/build/reports/jacoco/test/jacocoTestReport.xml,
            tethys-util/build/reports/jacoco/test/jacocoTestReport.xml
        ###------------ 构造 Docker 镜像
      - run: ./gradlew :db:buildImage
      - run: ./gradlew :tethys-im-server:buildImage
      - run: ./gradlew :tethys-rest-server:buildImage
      - name: Docker push
        run: |
          PROJECT_VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push kevin70/tethys-im:latest
          docker push kevin70/tethys-im:$PROJECT_VERSION
          docker push kevin70/tethys-rest:latest
          docker push kevin70/tethys-rest:$PROJECT_VERSION
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ###------------ Sonarqube
      - name: sonarqube analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: |
            tethys-im-server/build/libs
            tethys-rest-server/build/libs
